language: cpp
dist: focal
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-10
    - g++-10
    - libsdl2-dev
    - libsdl2-ttf-dev
    - libasound2-dev
    - libxinerama-dev
    - libxi-dev
    - qt5-default
    update: true
  homebrew:
    packages:
    - sdl2
    - sdl2_ttf
    update: true
jobs:
  include:
    - os: osx
      osx_image: xcode11.6
      compiler: clang
      env: SUBTARGET=ci   MAME=mameci64
    - os: linux
      arch: amd64
      compiler: gcc
      env: SUBTARGET=ci   MAME=mameci64
    - os: linux
      arch: arm64
      compiler: gcc
      env: SUBTARGET=ci   MAME=mameci
    - os: linux
      arch: s390x
      compiler: gcc
      env: SUBTARGET=ci   MAME=mameci64
    - os: linux
      arch: ppc64le
      compiler: gcc
      env: SUBTARGET=ci   MAME=mameci64
  allow_failures:
    - arch: ppc64le
  fast_finish: true
script:
  - if [ $TRAVIS_OS_NAME == 'linux' ]; then
    if [ $CC == 'clang' ]; then
    make -j2 IGNORE_GIT=1 OVERRIDE_CXX="clang++-3.6" OVERRIDE_CC="clang-3.6" TOOLS=1 && ./$MAME -validate;
    else make -j4 IGNORE_GIT=1 OPTIMIZE=0 OVERRIDE_CC="gcc-10" OVERRIDE_CXX="g++-10" TOOLS=1 && ./$MAME -validate;
    fi
    elif [ $TRAVIS_OS_NAME == 'osx' ]; then
    unset LDOPTS && make -j2 OPTIMIZE=0 USE_LIBSDL=1 TOOLS=1 && ./$MAME -validate;
    fi
branches:
  only:
    - master
notifications:
  email: false

