shallow_clone: true

os:
  - Visual Studio 2017

environment:
  matrix:
  - TOOLSET: vs2015
  - TOOLSET: vs2017

configuration:
  - Debug
  - Release

install:
  - git clone https://github.com/bkaradzic/bx ..\bx
  - ..\bx\tools\bin\windows\genie --with-tools %TOOLSET%

build:
  project: .build/projects/$(TOOLSET)/bimg.sln
