name: MAME-libretro Android ARMv7

on:
  push:
    branches:
      - master

jobs:
  AndroidARMv7:
    name: Build for Android ARMv7
    runs-on: ubuntu-latest

    env:
      ANDROID_NDK_VERSION: "21.3.6528147"
      ANDROID_NDK_ROOT:    ${ANDROID_HOME}/ndk/${ANDROID_NDK_VERSION}
      ANDROID_NDK_LLVM:    ${ANDROID_NDK_ROOT}/toolchains/llvm/prebuilt/linux-x86_64
      ANDROID_NDK_ARM:     ${ANDROID_NDK_ROOT}/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64

    steps:    
    - name: Install Android NDK
      run: echo "y" | sudo ${ANDROID_HOME}/tools/bin/sdkmanager --install "ndk;${ANDROID_NDK_VERSION}"
    - uses: actions/checkout@v2
    - run: make -f Makefile.libretro platform=android -j8
    # - run: strip -s mame_libretro_android.so
    - run: zip -9 mame_libretro.zip mame_libretro_android.so
    - name: Upload MAME core
      uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        automatic_release_tag: Android_ARMv7
        prerelease: false
        title: Android ARMv7
        files: |
          mame_libretro.zip
    - name: Save core for upload job
      uses: actions/upload-artifact@v2
      with:
        name: mame_libretro.zip
        path: mame_libretro.zip
  
  uploadToBB:
    name: Upload core to buildbot
    runs-on: ubuntu-latest
    needs: AndroidARMv7
    
    steps:
    - name: Recover core from artifacts
      uses: actions/download-artifact@v2
      with:
        name: mame_libretro.zip
        path: .
    - name: Upload to buildbot
      id: deploy
      uses: Pendect/action-rsyncer@v1.1.0
      env:
        DEPLOY_KEY: ${{ secrets.KEY }}
      with:
        flags: '-vazr --delete'
        options: ''
        ssh_options: '-p ${{ secrets.PORT }}'
        src: mame_libretro.zip
        dest: '${{ secrets.USERNAME }}@${{ secrets.HOST }}:${{ secrets.ANDROID_ARMEABI_V7A_PATH }}'
