name: CI (macOS)

on: [push, pull_request]

jobs:
  build-macos:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@master
      - name: Install dependencies
        run: brew install python3 sdl2
      - name: Build
        env:
          USE_LIBSDL: 1
          TOOLS: 1
        run: make -j2
      - name: Validate
        run: ./mame -validate
      - uses: actions/upload-artifact@master
        with:
          name: mame-macos-${{ github.sha }}
          path: mame
