name: CI (macOS)

on:
  push:
    paths:
    - '.github/workflows/**'
    - '3rdparty/**'
    - 'scripts/**'
    - 'src/**'
    - 'COPYING'
    - 'makefile'
  pull_request:
    paths:
    - '.github/workflows/**'
    - '3rdparty/**'
    - 'scripts/**'
    - 'src/**'
    - 'COPYING'
    - 'makefile'

permissions:
  contents: read

jobs:
  build-macos:
    runs-on: macOS-latest
    permissions: 
        actions: write
    steps:
    - uses: actions/checkout@main
      with:
        fetch-depth: 0
    - name: Install dependencies
      run: brew install sdl2
    - name: Setup ccache
      uses: Chocobo1/setup-ccache-action@v1.5.2      
    - name: Prepare for complay cache
      run: |
          grep complay makefile >complay.prehash
          cat scripts/build/complay.py >>complay.prehash
    - name: cache complay-ed layouts
      uses: actions/cache@v3
      with:
          path: ${{ github.workspace }}/build/generated/mame/layout
          key: complay_${{ hashFiles('complay.prehash','**.lay') }}
    - name: Touch complay-ed layouts
      continue-on-error: true
      run: |
        cd build/generated/mame/layout && touch *.lh
    - name: Build
      env:
        USE_LIBSDL: 1
        SOURCES: sinclair/sprinter.cpp,sinclair/tsconf.cpp,sinclair/specnext.cpp,sinclair/pentevo.cpp,sinclair/spectrum.cpp,sinclair/spec128.cpp,sinclair/specpls3.cpp,sinclair/scorpion.cpp
        TOOLS: 1
        PRECOMPILE: 0
        DEBUG: 0
      run: make -j2
    - uses: actions/upload-artifact@main
      with:
        name: mame-macos-${{ github.sha }}
        path: |
          mame
        if-no-files-found: error
