name: MAME-libretro CI on Pull Requests

on:
  pull_request:
    branches:
      - master

env:
  SUBTARGET: ci
  MAME: mameci64

jobs:
  Linux:
    name: Build for Linux
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run: sudo apt install build-essential mesa-common-dev
    - run: make -f Makefile.libretro -j8
        
  Windows:
    name: Build for Windows
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}

    steps:
    - uses: msys2/setup-msys2@v2
      with:
        update: true
        install: wget git make mingw-w64-x86_64-binutils mingw-w64-x86_64-toolchain mingw-w64-x86_64-zlib mingw-w64-x86_64-pkg-config mingw-w64-x86_64-python2 zip p7zip
    - uses: actions/checkout@v2
    - name: Build libretro mame core
      env:
        MINGW64: "/mingw64"
      run: make -f Makefile.libretro -j8

  macOS:
    name: Build for macOS
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - run: make -f Makefile.libretro -j8

  AndroidARMv7:
    name: Build for Android ARMv7
    runs-on: ubuntu-latest

    env:
      MAME: mameci
      ANDROID_NDK_VERSION: "21.3.6528147"
      ANDROID_NDK_ROOT:    ${ANDROID_HOME}/ndk/${ANDROID_NDK_VERSION}
      ANDROID_NDK_LLVM:    ${ANDROID_NDK_ROOT}/toolchains/llvm/prebuilt/linux-x86_64
      ANDROID_NDK_ARM:     ${ANDROID_NDK_ROOT}/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64

    steps:
    - name: Install Android NDK
      run: echo "y" | sudo ${ANDROID_HOME}/tools/bin/sdkmanager --install "ndk;${ANDROID_NDK_VERSION}"
    - uses: actions/checkout@v2
    - run: make -f Makefile.libretro platform=android-arm -j8

  AndroidARM64:
    name: Build for Android ARM64
    runs-on: ubuntu-latest

    env:
      MAME: mametiny
      ANDROID_NDK_VERSION: "21.3.6528147"
      ANDROID_NDK_ROOT:    ${ANDROID_HOME}/ndk/${ANDROID_NDK_VERSION}
      ANDROID_NDK_LLVM:    ${ANDROID_NDK_ROOT}/toolchains/llvm/prebuilt/linux-x86_64
      ANDROID_NDK_ARM:     ${ANDROID_NDK_ROOT}/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64
      ANDROID_NDK_ARM64:   ${ANDROID_NDK_ROOT}/toolchains/aarch64-linux-android-4.9/prebuilt/linux-x86_64

    steps:
    - name: Install Android NDK
      run: echo "y" | sudo ${ANDROID_HOME}/tools/bin/sdkmanager --install "ndk;${ANDROID_NDK_VERSION}"
    - uses: actions/checkout@v2
    - run: make -f Makefile.libretro platform=android-arm64 -j8